### ISSUE TITLE
mongodb configuration 

### ISSUE THREAD

**Issue by mwangaz** [Developer-Autodesk/view.and.data-nodejs-mongo.sample#3]
Hi Philippe Leefsma
To deploy your sample in my environment, do I need to relocate seat.dwf and model.json file to my local database file? What if I want to use my own model and data? 
If I just put my  API credentials and mongoDB credentials and follow your instructions, the demon cannot work at all. I really need your help on this. Thanks in advance. 

Best Regards,

**Comment by leefsmp** [comment]
Hi I've been working on a complete new and cleaner version of that sample at [https://github.com/Autodesk-Forge/forge-rcdb.nodejs](https://github.com/Autodesk-Forge/forge-rcdb.nodejs)

I would not recommend to use that mongo sample, however if you want to test it on your side, you need to first upload a model of your choice to the Autodesk Cloud and make it available to load in the viewer, the DB only contains the URN of the model and info about the materials. See the documentation of the viewer API at [https://developer.autodesk.com/en/docs/viewer/v2](https://developer.autodesk.com/en/docs/viewer/v2)

Let me know if you have more specific questions

**Comment by mwangaz** [comment]
Hi leefsmp, I have studied your new sample and if I only change the client ID and secrete in config. file, there would be mistakes when running the "npm run build-dev" command as shown in the screenshot. Should I modify any other things in the sample so that I can test the app on my side? 
Actually what I want to realize is to show the my databse information of my own model in the property panel. Would you give more guidance on this one? 
Thanks a lot!
![qq 20161028205436](https://cloud.githubusercontent.com/assets/23032016/19808050/79728aea-9d55-11e6-9b3d-d2eb54670870.png)

**Comment by leefsmp** [comment]
On windows I found out that "NODE_ENV=xxx cmd" will fail, you have to use "set" in front of, so it would be the following command to run a dev build:

      `set NODE_ENV=development node bin\build.js`

Apart from that, you need to run a mongoDB database either locally or on the Cloud, import data from the two collections that you can find in resources/db (of course you can use your own data if you want to), and modify the development.config.js file accordingly to your settings

**Comment by mwangaz** [comment]
Hi Philippe, sorry to disturb you again but the command still can not run correctly. I have modified the development.config.js file and production.config.js file. 
If I run "set NODE_ENV=development (or production) node bin\build.js" there is no response, as shown in the screenshot. If I run "npm install", there are errors saying "NODE_ENV" is not recognized as an internal or external command. What's the problem then? Thanks a lot!
![qq 20161102092141](https://cloud.githubusercontent.com/assets/23032016/19913562/bb00d5ac-a0de-11e6-95ed-ab2ec436f729.png)
